project_id = "ligsikirufdbhhahiyks"

[functions.send-appointment-reminder]
verify_jwt = false

[functions.ai-analytics]
verify_jwt = false

[functions.expense-notification]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true
